/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: EdDeasy (https://sketchfab.com/EdDeasy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/alien-29b88bd5e48145d59b7a248e9f9608a8
Title: ALIEN
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export  default function Alien(props) {
  const { nodes, materials } = useGLTF("/models/alien-transformed.glb")

  const modelRef = useRef ()

   useFrame ((state, delta ,xrFrame) =>  {

    modelRef.current.position.y = .5 + Math.sin(state.clock.elapsedTime)*0.105




   })



  return (
    <group {...props} dispose={null}
  scale={[1,1,1]}
  position={[0,-2,0]}
  ref={modelRef}

    
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.alien_u0v0_alien_u0v0_0.geometry}
        material={materials.alien_u0v0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.alien_u0v1_alien_u0v1_0.geometry}
        material={materials.alien_u0v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.alien_u0v2_alien_u0v2_0.geometry}
        material={materials.alien_u0v2}
      />
    </group>
  )
}

useGLTF.preload("/models/alien-transformed.glb")
