/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mateusz Woliński (https://sketchfab.com/jeandiz)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/holometabolous-static-2740866a64f14aa8affc3798b51d5589
Title: 𝖍𝖔𝖑𝖔𝖒𝖊𝖙𝖆𝖇𝖔𝖑𝖔𝖚𝖘 [static]
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { Environment } from '@react-three/drei';
export  default function Man(props) {
  const { nodes, materials } = useGLTF("/models/scene-transformed.glb");

 const modelRef = useRef ()
   

   useFrame((state, delta, xrFrame) => {
       modelRef.current.position.y = -1.5 + Math.sin(state.clock.elapsedTime)*0.15;
  })




  return (
    <group {...props} dispose={null}
    ref={modelRef}
    position={[0,-1.5,0]}
    scale={[2 ,2,2]}
    rotation={[0.25,0,0]}
    Environment={["dawn"]}
    
    
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh_001_Buttons_001_0.geometry}
        material={materials.Buttons_001}
        position={[0.01, -0.197, 0.066]}
        scale={0.01}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.QS1490_W01_1_1_002_QS1490_W01_1_1_001_0.geometry}
        material={materials.QS1490_W01_1_1_001}
        position={[0.06, 1.179, 0.195]}
        rotation={[-1.539, -0.067, 0.011]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pngimg_com___moth_PNG31_002_Moth__Texture_0.geometry}
        material={materials.Moth__Texture}
        position={[0.139, 1.17, 0.337]}
        rotation={[0, 1.387, 0]}
        scale={0.086}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.human_HighPolyEyesMesh_001_human_HighPolyEyes_001_0.geometry}
        material={materials.human_HighPolyEyes_001}
        position={[0, 0.818, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.human_eyelashes02Mesh_001_human_eyelashes02_001_0.geometry}
        material={materials.human_eyelashes02_001}
        position={[0, 0.818, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.human_female_genericMesh_001_human_body_001_0.geometry}
        material={materials.human_body_001}
        position={[0, 0.818, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.human_eyebrow001Mesh_001_human_eyebrow001_001_0.geometry}
        material={materials.human_eyebrow001_001}
        position={[0, 0.818, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.human_Teeth_BaseMesh_001_human_Teeth_Base_001_0.geometry}
        material={materials.human_Teeth_Base_001}
        position={[0, 0.818, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.human_tongue01Mesh_001_human_tongue01_001_0.geometry}
        material={materials.human_tongue01_001}
        position={[0, 0.818, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus_Material_002_0.geometry}
        material={materials.Material_002}
        position={[-0.021, 1.537, -0.062]}
        rotation={[-3.12, 0.006, 0.168]}
        scale={0.146}
      />
    </group>
  )
};

useGLTF.preload("/models/scene-transformed.glb")
