/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: felipegall (https://sketchfab.com/felipegall)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hardhead-a8e22c7c8bcc4a5a83b2cb72e74c88f2
Title: Hardhead
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Robot(props) {
  const { nodes, materials } = useGLTF("/models/hard-transformed.glb")

  const modelRef = useRef ();

  useFrame (() =>{
      modelRef.current.rotation.y += 0.007
  
  })
  


  
  return (
    <group {...props} dispose={null}
    ref={modelRef}
    scale={[2,2,2]}
    position={[0,-1,0]}
    
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Final}
        scale={0.141}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.OUTLINE}
        scale={0.141}
      />
    </group>
  )
}

useGLTF.preload("/models/hard-transformed.glb")
