/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: 3D_Star Galactica (https://sketchfab.com/3D_Star_Galactica)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/bsg-ragnar-anchorage-f76fe807ae894db899a280d958902027
Title: BSG - Ragnar Anchorage
*/

"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Build(props) {
  const { nodes, materials } = useGLTF("/models/built-transformed.glb")
  const modelRef = useRef ();

useFrame (() =>{
    modelRef.current.rotation.y += 0.007

})


  return (
    <group {...props} dispose={null}
    scale={[.00191250 ,.00191250, .00191250]}
    position={[0,2,0]}
    ref={modelRef}
    
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Spire_P1001_Ragnar_Spire_P1_0.geometry}
        material={materials.Ragnar_Spire_P1}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Spire_P2_Ragnar_Spire_P2_0.geometry}
        material={materials.Ragnar_Spire_P2}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Spire_P3_Ragnar_Spire_P3_0.geometry}
        material={materials.Ragnar_Spire_P3}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Spire_P4_Ragnar_Spire_P4_0.geometry}
        material={materials.Ragnar_Spire_P4}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Spire_Struts_Ragnar_Spire_Struts_0.geometry}
        material={materials.Ragnar_Spire_Struts}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Spire_Greeble_1_Ragnar_Spire_Greeble_1_0.geometry}
        material={materials.Ragnar_Spire_Greeble_1}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Spire_Antenna_Ragnar_Spire_Antenna_0.geometry}
        material={materials.Ragnar_Spire_Antenna}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Spire_Covers_Ragnar_Spire_Covers_0.geometry}
        material={materials.material_0}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Spire_Greeble_2_Ragnar_Spire_Greeble_2_0.geometry}
        material={materials.Ragnar_Spire_Greeble_2}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Docking_Ports_Ragnar_Docking_Ports_0.geometry}
        material={materials.Ragnar_Docking_Ports}
        position={[0, 1.387, 0]}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Ring_Arms003_Ragnar_Ring_Arms_0.geometry}
        material={materials.Ragnar_Ring_Arms}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Inner_Ring003_Ragnar_Inner_Ring_0.geometry}
        material={materials.Ragnar_Inner_Ring}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Ring_Segment001_Ragnar_Ring_Segment_0.geometry}
        material={materials.Ragnar_Ring_Segment}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Ring_Connector001_Ragnar_Ring_Connector_0.geometry}
        material={materials.material_1}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Ring_Segment_Connection001_Ragnar_Ring_Segment_Connection_0.geometry}
        material={materials.Ragnar_Ring_Segment_Connection}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Ring_Segment_Greeble001_Ragnar_Ring_Segment_Greeble_0.geometry}
        material={materials.Ragnar_Ring_Segment_Greeble}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Ring_Segment_Plating001_Ragnar_Ring_Segment_Plating_0.geometry}
        material={materials.Ragnar_Ring_Segment_Plating}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Ring_SegmentDestr001_Ragnar_Ring_SegmentDestr_0.geometry}
        material={materials.Ragnar_Ring_SegmentDestr}
        position={[0, 364.027, 0]}
        rotation={[0, Math.PI / 3, 0]}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Ragnar_Ring_SegmentDestr_Rebar001_Ragnar_Ring_SegmentDestr_Rebar_0.geometry}
        material={materials.Ragnar_Ring_SegmentDestr_Rebar}
        position={[0, 364.145, 0]}
        rotation={[0, Math.PI / 3, 0]}
        scale={20}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Credits_EVE-Kaneda_NepsterCZ_Credits_EVE-Kaneda_NepsterCZ_0'].geometry}
        material={materials.material_2}
        position={[-0.731, 503.746, 0]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[761.122, 761.122, 76.112]}
      />
    </group>
  )
}

useGLTF.preload("/models/built-transformed.glb")
